Update Introduction
sirixdb/sirixdb.github.io pull request #14
Opened 2021-04-26 16:34 UTC by adnanmorsy97

I have fixed some spelling and grammar mistakes

2021-04-26 20:16 UTC, adnanmorsy97 commented
@JohannesLichtenberger could you please merge it :) ?

2021-04-28 14:48 UTC, mosheduminer requested changes

2021-04-28 14:48 UTC, mosheduminer commented on documentation.md
> +Usually, database systems either overwrite data in place or do a copy-on-write operation followed by the removal of the outdated data. The latter may be some time later from a background process. Dat
> Application or the valid time

This is incorrect. Perhaps "Application (also known as "valid") time

2021-04-28 14:48 UTC, mosheduminer commented on documentation.md
> +SirixDB is very space-efficient. Depending on the versioning algorithm, it only copies changed records plus possibly a few more during writes. Thus, SirixDB, for instance, usually does not copy a who
> cluster-related

This is definitely meant to be "cluster related". Please change this back.

2021-04-28 14:48 UTC, mosheduminer commented on documentation.md
> +SirixDB is a storage system, which brings versioning to a sub-file granular level while taking full advantage of flash-based drives as SSDs. As such, per revision as well as per page deltas are store
Brackit is the name of the XQuery processor, not Bracket. Please change this back.

2021-04-28 14:48 UTC, mosheduminer commented on documentation.md
> -1. The [transactional cursor API](/transactional-cursor-api.html) is a powerful low-level API.
It looks like the only change here is the removal the the link. Why remove the link? Please change this back.

2021-04-28 14:48 UTC, mosheduminer commented on documentation.md
> +- [Pushing Database Versioning to Its Limits using a Novel Sliding Snapshot Algorithm and Efficient Time Travel Queries](https://medium.com/sirixdb-sirix-io-how-we-built-a-novel-temporal/why-and-how-
Please don't change the titles of the articles, this is title under which the article was published.

2021-04-28 14:48 UTC, mosheduminer commented on documentation.md
> -- [Temporal REST, How to really exploit XML](http://nbn-resolving.de/urn:nbn:de:bsz:352-opus-84476) (IADIS WWW/Internet08)
Please change this back. It is the title under which the paper was published.

2021-04-28 14:48 UTC, mosheduminer commented on documentation.md
> +- [Distributing XML with a focus on parallel evaluation](http://nbn-resolving.de/urn:nbn:de:bsz:352-opus-84487) (DBISP2P08)
Please change this back. It is the title under which the paper was published.

2021-04-29 10:10 UTC, adnanmorsy97 commented
Hey @mosheduminer, thank you for your hints. I edited everything, that you have mentioned. Could you please read it again and if everything is correct, could you merge it ?

2023-07-12 22:22 UTC, closed without merging