Update "Concepts"
sirixdb/sirixdb.github.io pull request #16
Opened 2021-04-26 19:39 UTC by adnanmorsy97

I have fixed some spelling and grammar mistakes.

2021-04-26 20:16 UTC, adnanmorsy97 commented
@JohannesLichtenberger could you please merge it :) ?

2021-04-28 15:13 UTC, mosheduminer requested changes

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +**Each node and revision in SirixDB is referenced by a unique, stable identifier.** First, SirixDB has to find the revision by its revision number traversing a tree of indirect pages. Addressing node
I think this should best be changed to `indirection pages`. What do you think @JohannesLichtenberger?

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +: The `RevisionRootPage` is the main entry point to a revision. It stores the author-ID, an optional commit message, and a timestamp in the form of the unix epoch (milliseconds since 1970). Furthermo
I feel like this paragraph is unclear and could be improved, but I don't understand what is going on here. @JohannesLichtenberger?

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +To support fast access to a `RevisionRootPage`, SirixDB stores a second file with just the offsets to specific revisions in a revisions file, which is read into main-memory on startup.
I think it should be left as `revisions-file`, consistent with the usage of `data-file` in this document, for example.

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +: The `PathPage` has references to `IndirectPages`, whereas each of the indirect pages is the root entry point to a user-defined path index. A unique index ID is also the reference offset in the path
I think the term is `IndirectPage`, so perhaps the old way is preferable.

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +: `RecordPage`s store the actual data. Currently, SirixDB stores 512 records on a record page. Each record page has a pointer to the previous record page, which stores the offset of the previous vers
The correct usage here is `in`, not `on`, please change this back.

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +However, potentially only a small fraction of records on the page have to be retrieved and reconstructed from byte-arrays in-memory for reads. SirixDB can delay this reconstruction until a transactio
Again, please change this back.

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +: `RecordPage`s store the actual data. Currently, SirixDB stores 512 records on a record page. Each record page has a pointer to the previous record page, which stores the offset of the previous vers
When dealing with a real page, you would be probably be correct, that it should be `on`, however, the conventional usage in regards to memory pages is `in`, I believe.

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +We assume that a read-write transaction modifies a record in the leftmost *RecordPage*. Depending on the versioning algorithm used by SirixDB, the modified record, as well as probably some other reco
> page structure

given that structure here describes the page ("the page, which is a structure"), it's probably better to use `page-structure` .

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +SirixDB also stores checksums in the parent pointers as in ZFS. Thus, the storage engine in the future will be able to detect data corruption and heal itself, once we partition and replicate the data
Again, please change this back.

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +All changed RecordPages are written to persistent storage, starting with the leftmost. If other changed record pages exist underneath an indirect page, SirixDB serializes these before the *IndirectPa
Why remove the italics from `*RecordPages*`? Please put them back.

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +Note that SirixDB has to update the ancestor path of each changed RecordPage. However, storing indirect pages as well as the *RevisionRootPage*, *CASPage*, *PathSummaryPage*, and the *PathPage* is ch
Please put back the italics (`*`) and change back the apostrophe.

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +One of the most distinctive features of SirixDB is that it versions the RecordPages. It doesn’t merely copy all records of the page, even if a transaction only modifies a single record. The new recor
Please put back the italics (*) and change back the apostrophe.

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +SirixDB stores at most a fixed number of records. That is the actual data per database page (currently limited to 512 records). The records themselves are of variable size. Overlong records, which ex
I think database-page is a particular kind of page, and warrants the use of the hyphen (`-`).

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +- only the changed records in a record page regarding the former version (incremental)
Please put the hyphen back (similar to database-page).

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +Differential-versioning tries to balance reads and writes a bit better, but is still not optimal. A system, implementing a differential versioning strategy has to write all changed records since a pa
Please change record-page back.

2021-04-28 15:13 UTC, mosheduminer commented on concepts.md
> +The algorithm makes use of a sliding window. First, any changed record must be written during a commit. Second, any record, which is older than a predefined length N of the window and which has not b
Please change back the apostrophe.

2021-04-28 15:41 UTC, JohannesLichtenberger commented on concepts.md
> +A temporal database is capable of retrieving past states. Typically it stores the transaction time; that is the time a transaction commits data. If the valid time is also stored, that is when a fact
Or maybe "which means two time axis", but I'm not sure about this.

2021-04-29 09:52 UTC, adnanmorsy97 commented
Hey @mosheduminer thank you for your hints. I edited everything, that you have mentioned. Could you please read it again and if everything is correct, could you merge it ?

2023-07-12 22:22 UTC, closed without merging